name: nightly

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22
        cache: false

    - name: Build
      run: make build-all DIST=nightly

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/nightly/linux
        name: midiasm_linux-x64-nightly.zip

    - name: Upload MacOS Intel artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/nightly/darwin-x64
        name: midiasm_darwin-x64-nightly.zip

    - name: Upload MacOS Apple silicon artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/nightly/darwin-arm64
        name: midiasm_darwin-arm64-nightly.zip

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/nightly/windows
        name: midiasm_windows-nightly.zip

    - name: Upload ARM artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/nightly/arm
        name: midiasm_arm-nightly.zip

    - name: Upload ARM7 artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/nightly/arm7
        name: midiasm_arm7-nightly.zip
